---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  projectUrl:
    Description: "Git project URL. (https://github.com/<your-name>/java-project.git)"
    Type: "String"

  webami:
    Description: "Web server AMI."
    Type: "String"
    Default: "ami-01cc34ab2709337aa"

  webtype:
    Description: "Web server instance type"
    Type: "String"
    Default: "t2.micro"

  asgsize:
    Description: "ASG size."
    Type: "String"
    Default: "2"

  GitHubBranchName:
    Description: "GitHub branch name"
    Type: "String"
    Default: "master"

  GitHubRepositoryName:
    Description: "GitHub repository name"
    Type: "String"
    Default: "python-project"

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DenyUnEncryptedObjectUploads"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Join ["", [!GetAtt ArtifactBucket.Arn, "/*"]]
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"

  CodestarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: GitHubConnection
      ProviderType: GitHub

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: "Environment"
          Value: "Test"

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
    
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: ""

  ElbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref Vpc
      GroupDescription: "Allow http access from everywhere"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"

  WebserverSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref Vpc
      GroupDescription: "Allow port 80 from ELB"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !GetAtt ElbSG.GroupId

  InternetGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: stack
        Value: codedeploy

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGW
      VpcId: !Ref Vpc

  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId: !Ref PublicRT
      GatewayId: !Ref InternetGW
    DependsOn:
      - InternetGW

  PublicSubnet1RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT
      SubnetId: !Ref PublicSubnet2

  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: "idle_timeout.timeout_seconds"
          Value: "30"
      Name: !Join [ "", [ !Ref "AWS::StackName", "-alb"  ] ]
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref ElbSG
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Join ["", [ !Ref "AWS::StackName", "-alb"]]

  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ELBTargetGroup
          Type: "forward"
      LoadBalancerArn: !Ref ELB
      Port: "80"
      Protocol: "HTTP"

  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: "/"
      HealthCheckProtocol: "HTTP"
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: "instance"
      Port: 80
      Protocol: "HTTP"
      VpcId: !Ref Vpc

  WebGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: !Ref asgsize
      LaunchConfigurationName: !Ref WebLaunchConf
      MaxSize: !Ref asgsize
      MinSize: !Ref asgsize
      Tags:
        - Key: "Name"
          PropagateAtLaunch: "true"
          Value: "webapp"
        - Key: "Role"
          PropagateAtLaunch: "true"
          Value: "webserver"
      TargetGroupARNs:
        - !Ref ELBTargetGroup
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  WebInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WebInstanceRole

  WebLaunchConf:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: "true"
      IamInstanceProfile: !Ref WebInstanceProfile
      ImageId: !Ref webami
      InstanceType: !Ref webtype
      SecurityGroups:
        - !Ref WebserverSG
      UserData:
        !Base64 |
          #!/bin/bash
          yum -y update
          yum install -y git
          yum install -y ruby
          yum install -y wget
          amazon-linux-extras install nginx1.12 -y
          systemctl enable nginx.service
          systemctl start nginx.service
          cd /home/ec2-user
          wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          service codedeploy-agent start
          rm install

  WebInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - "arn:aws:iam::aws:policy/AWSCodeDeployFullAccess"
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: "Allow"
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Join ["", [!GetAtt "ArtifactBucket.Arn", "/*"]]
                Action:
                  - "s3:GetObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
            Version: "2012-10-17"
          PolicyName: "ec2codedeploy"

  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: "CODEPIPELINE"
      Description: "pipeline build project"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        ImagePullCredentialsType: "CODEBUILD"
        Type: "LINUX_CONTAINER"
      ServiceRole: !GetAtt AppBuildRole.Arn
      Source:
        Type: "CODEPIPELINE"

  AppBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "CodeBuildAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
              - Effect: "Allow"
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Join ["", [ !GetAtt ArtifactBucket.Arn, "/*"]]
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
              - Effect: "Allow"
                Action: "codestar-connections:UseConnection"
                Resource: !Ref CodestarConnection

  BuildLogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "BuildLogAccess"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource:
              - !Sub
                - "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${project}"
                - project: !Ref AppBuildProject
              - !Sub
                - "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${project}:*"
                - project: !Ref AppBuildProject
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
      Roles:
        - !Ref AppBuildRole

  WebPlatformApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
        ComputePlatform: "Server"

  WebPlatformDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref WebPlatformApplication
      AutoScalingGroups:
        - !Ref WebGroup
      DeploymentConfigName: "CodeDeployDefault.OneAtATime"
      DeploymentStyle:
        DeploymentOption: "WITH_TRAFFIC_CONTROL"
        DeploymentType: "IN_PLACE"
      LoadBalancerInfo:
        TargetGroupInfoList:
          - Name: !GetAtt ELBTargetGroup.TargetGroupName
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn

  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "codedeploy.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"

  AppCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: "S3"
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages:
        - Name: "Source"
          Actions:
            - Name: "GetSource"
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "CodeStarSourceConnection"
                Version: "1"
              Configuration:
                ConnectionArn: !Ref CodestarConnection
                FullRepositoryId: !Ref GitHubRepositoryName
                BranchName: !Ref GitHubBranchName
                DetectChanges: true
              OutputArtifacts:
                - Name: "SourceCode"
        - Name: "Build"
          Actions:
            - Name: "BuildSource"
              InputArtifacts:
                - Name: "SourceCode"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              Configuration:
                ProjectName: !Ref AppBuildProject
              OutputArtifacts:
                - Name: CodeArtifact
        - Name: "Deploy"
          Actions:
            - Name: "DeployArtifact"
              InputArtifacts:
                - Name: "CodeArtifact"
              ActionTypeId:
                Category: "Deploy"
                Owner: "AWS"
                Provider: "CodeDeploy"
                Version: "1"
              Configuration:
                ApplicationName: !Ref WebPlatformApplication
                DeploymentGroupName: !Ref WebPlatformDeploymentGroup

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
      Path: "/service-role/"
      Policies:
        - PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action:
                  - "codestar-connections:UseConnection"
                Resource: "*"
              - Effect: "Allow"
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Join ["", [!GetAtt ArtifactBucket.Arn, "/*"]]
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
              - Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplication"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeployment"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:RegisterApplicationRevision"
                Resource: "*"
                Effect: "Allow"
              - Action:
                  - "ec2:*"
                  - "elasticloadbalancing:*"
                  - "autoscaling:*"
                  - "cloudwatch:*"
                Resource: "*"
                Effect: "Allow"
              - Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource:
                  - !GetAtt AppBuildProject.Arn
                Effect: "Allow"
            Version: "2012-10-17"
          PolicyName: "ec2codedeploy"

Outputs:
  ELBEndpoint:
    Description: "ELB DNS endpoint address"
    Value: !GetAtt ELB.DNSName

  S3BucketDomain:
    Description: "S3 bucket domain name"
    Value: !GetAtt ArtifactBucket.DomainName
