---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  projectUrl:
    Description: "Git project URL. (https://github.com/<your-name>/java-project.git)"
    Type: "String"

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DenyUnEncryptedObjectUploads"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Join ["", [!GetAtt ArtifactBucket.Arn, "/*"]]
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"

  GitHubCreds:
    Type: AWS::CodeBuild::SourceCredential
    Properties: 
      Token: '{{resolve:secretsmanager:github-token:SecretString:token}}'
      ServerType: GITHUB
      AuthType: PERSONAL_ACCESS_TOKEN

  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Location: !Ref ArtifactBucket
        Type: "S3"
        OverrideArtifactName: "true"
        Name: "artifact.zip"
        Packaging: "ZIP"
      Description: "app build project"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        ImagePullCredentialsType: "CODEBUILD"
        Type: "LINUX_CONTAINER"
      ServiceRole: !GetAtt AppBuildRole.Arn
      Source:
        Auth:
          Resource: !Ref GitHubCreds
          Type: OAUTH
        Location: !Ref projectUrl
        Type: "GITHUB"
        ReportBuildStatus: "true"
      Triggers:
        Webhook: "true"

  AppBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "CodeBuildAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
              - Effect: "Allow"
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Join ["", [ !GetAtt ArtifactBucket.Arn, "/*"]]
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"

  BuildLogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "BuildLogAccess"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource:
              - !Sub
                - "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${project}"
                - project: !Ref AppBuildProject
              - !Sub
                - "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${project}:*"
                - project: !Ref AppBuildProject
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
      Roles:
        - !Ref AppBuildRole
