---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 30
      Tags:
        - Key: "Environment"
          Value: "Class"

Outputs:
  SqsUrl:
    Value: !Ref Queue
    Description: "SQS Url"
