:doctype: article
:blank: pass:[ +]

:sectnums!:

== Assignment 4
Jason Baker <bake2352@stthomas.edu>
1.0, 4/3/2016

=== Overview
This week we will get some hands-on experience with EC2 and S3. You have been
using EC2 for a couple weeks now, but this assignment will dive deeper into
its capabilities.

One of the challenges of an assignment like this is that the AWS web console
changes all the time without warning. Therefore, the instructions can't be too
tightly coupled to the AWS web interface. In other words, instead of telling
you exactly which link to select or button to push on the AWS web console, you
will need to make reasonable decisions as you work through the assignment.

If you get stuck on a step, do a little research on the AWS documentation site or
reach out to the class on Slack. Your feedback will be incorporated into future
versions of the assignment.

=== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

=== The assignment

Ready your engines. Let's rev up some instances!

==== Create a role

The first step in the assignment is to create a new role. We talked about
roles briefly in class. Basically, a role is a way to assign privileges to
a resource, such as an EC2 instance. A role lets you treat an instance kind
of like a user.

For example, you can create a role that allows access to data
stored on S3 and then assign this role to an EC2 instance. Applications running
on the EC2 instance can use the role to access S3 data without having to
store an access key and secret key. This represents a superior security configuration.

Let's create this S3 access role now.

  * Log into the AWS web console and select the *IAM* service.

  * Select the menu item to manage *Roles*.

  * Select the appropriate button or link to *create a new role*.

  * Give the role the name: *S3-full-access*

  * AWS supports several different types of roles. Your new role will be an
  *Amazon EC2* Service Role. Select the button or link corresponding to this role.

  * Each role type may have hundreds of policies associated with it. A policy is a
  configuration document which defines specific access privileges. You are looking
  for a policy called *AmazonS3FullAccess*. Usually you can filter the policy
  table listing by typing `s3` into a filter text input. Once you see the correct
  policy, check it and move on to the next step.

  * You should now be able to *create* the policy.

If you created the new role properly, you should see the `S3-full-access` role listed
in the IAM roles table.

==== Create an S3 bucket

Next, let's create an S3 bucket to store some data. Go ahead and select the S3
service on the AWS console. If you haven't created an S3 bucket before you might
see some sort of welcome message explaining the purpose of the S3 service.

  * Once you see the S3 dashboard, click the button or link to *create a bucket*.

  * Name your new S3 bucket: `<AWS username>-infrastructure-4`, where <AWS username>
  is your personal Amazon username. Also, select the `US Standard` region. Remember,
  S3 bucket names are universal which means that your bucket name has to be unique
  worldwide. On the off chance that your bucket name is already in use, just
  try a slightly different name.

.Example
----
jbaker-infrastructure-4
----

  * You should be able to select a button or link to *create* the bucket at this point.

==== Upload data to S3

You can upload files to S3 now that your new bucket is setup. Select your new bucket
on the S3 dashboard and look at its *properties*.

  * Select the *Tags* property and add a new tag with the key `Project` and the
  value `Assignment 4`. It's a good idea to tag resources you create on AWS. Tags
  can be any sort of key/value pair. Organizations use tags to track resources by
  tagging resources with an owner name, organizational unit, or budget ID.

  * Next, open a text editor on your local workstation and create a new file
  called `index.html`. The file should contain the following text:

----
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Infrastructure Assignment 4</title>
</head>

<body>
  <h1>My 4th Infrastructure Assignment</h1>
</body>
</html>
----

  * Select the appropriate button or link on the S3 console to *upload* a file
  to your new bucket. Either drag your `index.html` file into the browser or
  click the link to *add* the file to the bucket.

You should now see the `index.html` file listed in the bucket file listing. Did
you notice that you can also create folders inside S3 buckets? Folders are a
useful way to organize your data within buckets.

==== Encrypt S3 data

You can easily encrypt data that's stored on S3. When you uploaded your file to
the S3 bucket the data transfer occurred over an SSL/TLS-secured communications
channel. S3 encryption allows you to encrypt your data-at-rest. This prevents
someone from retrieving your data from the physical hard drive it's stored on.

  * Select your `index.html` file in the S3 console and look at its properties.
  To view the file's properties, you may need to select an *actions* button or
  link and then select a *properties* option.

  * Look at the file property *details*.

  * You should see a properties setting for *Server Side Encryption*. Set this
  property to *AES-256* and *save* the change.

AES-256 is the standard encryption algorithm used by Amazon to secure data in
many of its services.

==== Launch Linux server

The next step is to launch a Linux server using AWS EC2.
In previous assignments, you selected all of the server launch defaults when launching a
Linux instance. This time you will customize some of the launch settings. In particular,
you will associate the S3 role you created previously with the new instance. You
can only associate a role with an instance when it's being launched. The role cannot
be added later.

The server should have the following characteristics:

  * Amazon Linux AMI 64-bit (usually the first option listed)
  * Located in a U.S. region (us-east-1 or us-west-1)
  * t2.micro instance type
  *

Note that when you are launching the server, you can elect to use the same
key pair you used last week or you can create a new key pair for this
server. Either option is fine. From a practical standpoint, it might make
sense to reuse the same key pair each time so that you don't have to
keep track of which key pair you used to launch a particular server.

==== Taking a break

It's recommended that you complete this assignment in one sitting. But if
you need to work on it over the course of a couple days, that's no problem.
You can always `stop` your EC2 instance when you need to take a break, and
then `start` the instance back up when you are ready to work again. The
EC2 instances we are creating save our changes even when the instances are
shut down. Just don't `terminate` the instance, because then you will lose
all of your work and have to start all over again. AWS does not bill you
for instances that are stopped. Well, technically they bill you for the storage
costs of the instance, but that amounts to pennies per month.

==== Log into server
The next step is to log into the Linux server using a terminal program with
secure shell (SSH) support. You will need to have the server key and the
public IP address before attempting to log into the server.



==== Terminate server

The last step in the assignment is to terminate your Linux instance. AWS will bill you for every
hour the instance is running. The cost is nominal, but there's no need to rack
up unnecessary charges. Refer to the previous assignment if you don't remember
how to terminate your EC2 instance.

=== Submitting your assignment
You should have emailed me your GitHub username during the previous assignment.
There is no need to email your username again. I will review your published
work on GitHub after the homework due date.
