:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Assignment 10: Code pipeline
Jason Baker <bake2352@stthomas.edu>
1.1, 10/11/2017

== Overview
A DevOps code pipeline helps to automate continuous delivery processes for software development organizations. Developers, testers, and operations staff depend on functioning pipelines to transform code changes into deployable software releases. While software developers are the primary users of a pipeline, IT operations professionals oftentimes have to maintain it.

In this week's assignment, you will build a code deployment pipeline using Jenkins, a continuous integration tool. The pipeline will build, test, and deploy a very simple Java application.

This assignment is based off the Jenkins pipeline we created in class, so you can refer back to the lecture notes to build parts of the pipeline.

== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Let's get that code pipeline flowing!

=== Fork the Java application

The first step in the assignment is to fork the GitHub repository containing a Java application. Forking the repository will setup a copy of the repository in your personal GitHub account. You can then make changes to the application files in the repository without affecting the original (parent) repository.

Go to GitHub and fork the following repository by clicking on the *Fork* button:

  https://github.com/seis665/java-project

After a short period of time you should see a forked copy of this repository in your personal GitHub account.

=== Launch the Jenkins stack

You will use a CloudFormation template to launch a stack containing a Jenkins server. The stack will create the
following AWS resources:

* An AWS Virtual Private Cloud (VPC), including all the necessary routing tables and routes, an Internet gateway, and security groups for EC2 instances to be launched into.

* An Amazon EC2 instance that hosts a Jenkins server, installed and configured for you with all the necessary
plugins.

* All IAM service and instance roles required to setup an infrastructure pipeline.

Go to the AWS CloudFormation console and select the *Create Stack* button.

Choose a stack template by specifying the following S3 template URL:

  https://s3.amazonaws.com/seis665/jenkins-cf.json

On the *Specify Details* page, enter the following:

1. In *Stack name*, type a name for the stack. Choose something short and simple for easy reference.
2. In *JenkinsPassword*, provide an administrative password for this system (choose a hard password).
3. In *JenkinsUsername*, you can leave this set to `admin` or choose a different admin username.
4. In *Key Name*, choose the name of your Amazon EC2 key pair.
5. In *YourIP*, type the public IP address (appending /32) of the computer system which you will access the resources created by this template. If you do not know your current public IP address, you can open up a new web browser window and go to the URL: http://checkip.amazonaws.com/

Click the *Next* button.

On the *Options* page you can tag the resources created by the template. Feel free to create whatever tag you would like and click *Next*.

On the *Review* page, select the *I acknowledge that this template might cause AWS CloudFormation to create IAM resources check box*. (It will.) Review the other settings, and then choose *Create*.

It will take several minutes for CloudFormation to create the resources on your behalf. You can watch the progress messages on the *Events* tab in the console. When the stack has been created, you will see a CREATE_COMPLETE message in the *Status* column of the console and on the *Overview* tab.

You will find the IP address of the Jenkins server in the stack
outputs (select the stack name at look at the outputs tab). Log into
the Jenkins server with a web browser on port 8080:

  http://<Jenkins IP address>:8080

Log into the server using the username and password you provided
during the stack creation process.

Congratulations! You've created the infrastructure required to build a code pipeline.

=== Setup GitHub integration

Before you start working on a build pipeline, you should configure Jenkins to integrate with your GitHub account. This will allow Jenkins to automatically pull source code from your forked Java repository during the pipeline build stage.

Here is a summary of the steps required to setup this integration. You can review the class lecture notes or online guides to understand the details.

  * Create a new personal access token in your GitHub account. The token should have `admin:repo_hook`, `repo`, and `repo:status` permissions.

  * Add a new GitHub server in the Jenkins system configuration settings.

  * Add credentials for the GitHub server configuration
    ** Kind: Secret Text
    ** Copy GitHub token into secret field

  * Remember to select the GitHub token credential in the GitHub server settings after adding it!

  * Click the Test connection button to verify that the credentials work and save the Jenkins system configuration.

=== Create a Pipeline

You will create a new build pipeline using the Jenkins Pipeline DSL. Jenkins supports two different types of Pipeline DSL formats: declarative and scripted. You should use the declarative format for this assignment.

Begin by creating a new Jenkins pipeline project called *java-pipeline*. The project will use the Java GitHub project you forked into your personal repository.

Setup a build trigger for this repository using the Github hook trigger for GITScm polling. Configure the project to create a pipeline (Pipeline script from SCM) based on file called Jenkinsfile located at the root (top) directory of the Java project.

Build the pipeline to verify that it is working properly. The pipeline should clone your Java git repository, run a set of unit tests, build the Java application, and produce a unit test report.

=== Extend the Pipeline



=== Check your work

Here is what the contents of your git repository should look like before final submission:

====
&#x2523; jenkins-screen.jpg +
&#x2517; stack.json +
====

=== Save your work



Create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/assignment-invitations/874ccbb14cf1edafbdf104af22f7812f



=== Terminate application environment

The last step in the assignment is to delete all the AWS resources created by the stack. You don't want to keep this stack running for a long time because the costs will accumulate.

Go to the CloudFormation dashboard, select your running stack, and choose the
delete option. Watch as CloudFormation deletes all the resources previously
created.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
