:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Assignment 11: Docker
Jason Baker <bake2352@stthomas.edu>
1.2, 4/7/2018

== Overview
Containers are revolutionizing the way we package and deploy applications. Traditionally, we would install applications on bare metal hardware or virtual machines in our computing environment. We would have to carefully place applications on infrastructure to minimize conflicting requirements such as different versions of shared libraries. Containers let us partition applications and related dependencies on a shared computing platform.

In this week's assignment, you will build a server running Docker and explore how to manage containers on the system.

== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Let's start shipping those containers!

=== Build a Docker server

The first step in the assignment is to build a Docker server running on EC2 using the following CloudFormation template:

  https://s3.amazonaws.com/seis665/docker-single-server.json

Launch the template to create a new stack. Shell into the new EC2 instance and run the following command:

  $ docker --version

The system should respond with the docker client version. Something like:

  Docker version 17.06.2-ce, build 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3

=== Working with containers

Let's start by getting comfortable with the Docker command line. How about a Hello World application? Type in the following command:

  $ docker run busybox echo hello world

The system should respond back with the output `hello world`. What is happening here? Docker created a small container using the `busybox` image, executed single small process, and echoed the text `hello world`.

The process isn't running anymore. You can confirm that by running the command `docker ps`. You just ran an interactive process. Once the process completed, it stopped running. This might seem a little strange at first. Remember, containers are more like supercharged processes than like virtual machines.

Let's do something a little more sophisticated. Type in the following command:

  $ docker run -it ubuntu bash

This tells docker to load the `ubuntu` image and run the `bash` command. Additionally, docker was told to setup a virtual terminal connection to the container (-it). You should see the docker client download the ubuntu image and launch the container. It may take a minute or two the first time you run this command.

Now that you are in the container terminal, look around a little bit. Type in `ls /` to view the root directory. Containers have their own filesystem that overlays the filesystem on the host. Exit out of the container terminal by typing `exit`.

Notice that the container you just launched is now stopped (`docker ps`). This was an interactive container just like the first container you created. Try to run the container again, type:

  $ docker run -it ubuntu bash

Did you notice how much faster the container launched this time? That's because Docker is pretty smart about caching the different build layers of the container. It knew how to build the container this time because it cached all the layers from the previous container.

Next, let's launch a container that runs in the background. Type in the command:

  $ docker run -d -P --name web1 nginx

This will download and build a container running the popular `nginx` webserver. When you create a container, docker assigns it a long ID. It's not very easy to remember long ID strings, so using the `--name` parameter to assign a memorable name to containers is helpful.

You should see this container running on the system. Check the docker process list to confirm:

  $ docker ps

Look at the ports in the output that have been assigned to the web1 container.  You should see a a port mapping that looks similar to this: `0.0.0.0:32768->80/tcp`.  The nginx container image exposes port 80 in its dockerfile.  When you launched the container using the `-P` flag, docker assigned a random port number (32768), and mapped it to the exposed port 80 on the container.

Now, you should be able to retrieve the nginx test page using `curl`

  $ curl localhost:<PORT_NUMBER>

You should see the html of the nginx test page displayed.

=== Repository

Create a sub-directory in the ec2-user's home directory called `docker` and create a Git repository within this directory. Create another sub-directory within the `docker` directory called `html`. Create a small text file called `index.html` inside the `html` directory with the following content:

    <html>
    <body>
      <h1>My webserver</h1>
    </body>
    </html>

The directory structure and location of the `index.html` file should look something like this:

====
&#x2523;docker +
&#x2503;&#160;&#160;&#x2517; html +
&#x2503;&#160;&#160;&#160;&#160;&#x2517; index.html +
====

=== The Dockerfile

The Dockerfile is a handy way to encapsulate all the configuration commands required to build a single container. The remaining part of your assignment this week is to build a simple nginx webserver container using a Dockerfile. Create the `Dockerfile` in the `docker` directory. Here are the actions the Dockerfile should do:

  * The container must use the `nginx` image.
  * Set the maintainer of the Dockerfile to your name and email address.
  * The container should expose port 80.
  * Copy the files from the `html` directory you created earlier in the assignment to the /usr/share/nginx/html directory in the container.
  * The container should have an environment variable mapping the key `NGINX_PORT` to the value `80`.


=== Build Image Pipeline

It is a common practice to automate the building of Docker images using a CI/CD pipeline. Let's do that here as well.
Launch a Jenkins stack in the us-east-1 region using the following template:

  https://s3.amazonaws.com/seis665/jenkins-cf.json

Create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/assignment-invitations/eeea11fb5604fd931c30393c935aba6b

Create a new Jenkins pipeline job called `docker-pipeline` and configure it to use a Jenkinsfile located in your
Classroom repository. Note that since you are using a private repository for this assignment, you will need to enter
GitHub credentials for the git configuration in the pipeline job. Also, you will need to
reference these credentials in the git command used by your Jenkinsfile. This is pretty easy to
setup.

Please follow these steps to setup your GitHub access credentials in the pipeline job:

    * Create a GitHub personal access token (or use an existing token) in your personal GitHub account by going
    to the Settings->Developer Settings->Personal access tokens section on the GitHub site. Store this token 
    somewhere safe because you will need to enter it into the Jenkins configuration shortly. The token you create 
    should have the following scopes enabled:
        ** repo
        ** admin:repo_hook
    * When you are configuring the git settings for your pipeline job, click on the `Add` button by 
the credentials and select the `Jenkins` credential provider. 
    * Create a new `Username with password` credential, typing in your GitHub username and using the 
    personal access token as the password. 
    * Enter an identifiable value into the description field like `github account`. 
    * Click the `Add` button to add your GitHub credential.
    * Select your newly created credential in the `Credentials` drop-down field. If your credential works 
    properly for your private repo, you should not see a Jenkins login error message.
    * Note, you do not need to setup a pipeline build trigger or GitHub webhook for this assignment.

The pipeline job will use these credentials to access your private GitHub repository and retrieve a
Jenkinsfile. One of the first things the Jenkinsfile should do is tell Jenkins to clone the repository
using the `git` command. Let's use the `Pipeline Syntax` link at the bottom of the pipeline configuration
page to generate the proper syntax for this command.

    * Click on the `Pipeline Syntax` link at the bottom of the pipeline configuration page and select 
    the `git: Git` sample step. 
    * Type in your git repository URL (ending with `.git`).
    * Select the credentials you created earlier from the credentials drop-down field. If you select the 
    correct credentials, you should not see a Jenkins login error message.
    * Click the `Generate Pipeline Script` button. 
    * Copy-and-paste the generated code into your Jenkinsfile.

.Example:
----
git credentialsId: 'c868a19a-3de9-4ae1-9538-b832fd1c8b12', url: 'https://github.com/seis665/assignment-11-jasondbaker.git'
----

Your Jenkinsfile should have a single `Build` stage which uses the Dockerfile you created earlier in this assignment 
to build a new Docker image. Once you have the pipeline working properly, copy the console output from the last 
successful build into a file called `console.txt` and check it into the GitHub repository.

=== Check your work

Here is what the contents of your git repository should look like before final submission:

====
&#x2523; Dockerfile +
&#x2523; Jenkinsfile +
&#x2517; console.txt +

====


=== Terminate application environment

The last step in the assignment is to terminate your CloudFormation stacks on AWS.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
