:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Assignment 9: Configuration Management
Jason Baker <bake2352@stthomas.edu>
1.0, 11/12/2016

== Overview

Configuration management is an important methodology we use in IT to build and
maintain systems in our organizations. It helps us manage change more effectively
by leveraging key infrastructure as code principles. Instead of managing systems
with a complex graphical program storing data hidden away in a proprietary database,
we can use simple code scripts that are easy to read and place under version control.
In this assignment you will work with Ansible, one of the leading configuration
management tools in the marketplace.

== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Let's start managing configuration!

== Launch three instances

You will need to launch three EC2 instances for this assignment. We will configure the
first instance as a management server with the Ansible tool installed. The second
instance will become a webserver, and the third instance will become a MySQL database server.

Create a CloudFormation template to launch a stack with a VPC, subnet, routing
table, Internet gateway, and security group with the same configuration as the
previous assignment. Additionally, configure the template to launch three t2.micro EC2
instances named: mgmt1, web1, and database1. The servers should use the latest
Amazon Linux AMI. The CloudFormation template does not need to support any input
parameters, but it should output the public IP addresses of the web1 and database1
instances.

Additionally, the CloudFormation template should send a shell script via the
userdata property to the mgmt1 server which will automatically update all the current
software packages on the system and then install Ansible software. The following command
installs Ansible on an Amazon Linux system:

    pip install ansible

Once the three instances have finished launching, connect to the mgmt1 server and
verify that Ansible is installed:

    $ ansible

You should see some usage information for the ansible command. Next, create a
directory called `configuration` in your home directory. Create a git repository
in the configuration directory. This is where you will setup an Ansible playbook
and related configuration files. All files in this assignment should be setup
in this directory.

== Configure servers

You will use the Ansible software installed on mgmt1 to configure the web1 and
database1 systems. Ansible communicates with remote hosts using the SSH protocol
which means that the proper access credentials need to be in place on mgmt1 in
order to establish shell connections with the two other servers. Setup this
access now. You can test your credentials by trying to establish a shell connection
from mgmt1 to web1 and from mgmt1 to database1.

[NOTE]
We setup this type of access in a previous assignment, so review previous assignments if you don't remember how to setup this configuration.

Ansible uses an inventory file to track managed hosts. The inventory file specifies
how Ansible should connect to a remote host. It usually contains the IP address or
fully-qualified domain name of a host, as well as the username and key required to
access a host.

Create an inventory file called `hosts` and add the web1 and web2 hosts to this
file. Refer to the class lecture notes or the Ansible documentation to understand
the required format for this file. You will need to specify the username (ec2-user)
and private key required to connect to the remote host in the inventory file. Hint,
the argument used to specify the private key is `ansible_ssh_private_key_file`.

Now that you have an inventory file setup, let's tell Ansible to use this
inventory file. Ansible will look in the /etc/ansible directory for an inventory
file by default. We want Ansible to look in the new `hosts` file we created. Create
a new file called `ansible.cfg` and add the following contents:

    [defaults]
    inventory = /home/ec2-user/configure/hosts
    host_key_checking = False

At this point Ansible is configured to use the hosts file as an inventory. You
can verify that Ansible can successfully access the remote hosts by typing the
following commands:

    $ ansible web1 -m ping
    $ ansible database -m ping

If Ansible returns a successful `pong` for each host then you are ready to move
on! If not, then your `hosts` file is likely setup incorrectly. Carefully review
the configuration of your inventory file.

== Configure servers

You will create an Ansible playbook to configure the two remote hosts. Before beginning the playbook, take a look at the facts that Ansible can
collect from a remote host:

    $ ansible web1 -m setup

You will need to use a fact in your playbook, so take note of the fact variables that are returned by the setup module.

You can create a playbook file on the mgmt1 server using a local text editor like nano or vi. Alternatively, you can use your favorite source code editor on your local workstation and copy (scp) the file from your local workstation to the `configure` directory on mgmt1. Use whatever method is most comfortable for you.

Create a playbook called `playbook.yml` to perform the following tasks on each of the hosts:

    * Update the current software packages on the system.
    * Creae a variable called `administrator_name` with a value of `corpadmin` in the play.
    * Create a user with the value of the `administrator_name` variable on each system with a password (your choice).

Perform the following tasks on the web1 server:

    * Install the Nginx server package.
    * Copy the following `default.conf.j2` template to the system directory `/etc/nginx/conf.d/default.conf` substituting the text `example.com` with the name of the webserver (using a fact variable).


    server {
        listen       80;
        server_name  example.com;

        location / {
            root   /var/www/example.com/public_html/;
             index  index.html index.htm;
        }
    }

    * Ensure the nginx service is running and will automatically start during the system boot.

Perform the following tasks on the database1 server:

    * Install the mysql server package.
    * Configure the system to ensure mysql is running and will automatically start during the system boot.
    * Use a loop to configure 5 data backup directories called:
        ** /var/backup/data1
        ** /var/backup/data2
        ** /var/backup/data3
        ** /var/backup/data4
        ** /var/backup/data5

[WARNING]
Your playbook should only contain one software update task and one task to create a user called `corpadmin`. The play should apply each one of these tasks to multiple systems.

The `ec2-user` user doesn't have the necessary permissions to install new services on the instance. Ansible will need to become a super-user on these systems in order to install new packages.

Execute the playbook to configure the two hosts. If you encounter any error messages, review the playbook script and correct any mistakes.

=== Save your work

Create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/assignment-invitations/68c6b367013ed3711b1b1c9aa7bf8678

Commit your git repository (in the `configure` directory) to this repository.

=== Terminate application environment

The last step in the assignment is to delete all the AWS services you created.
Go to the CloudFormation dashboard, select your running stack, and choose the
delete option. Watch as CloudFormation deletes all the resources previously
created.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
