:blank: pass:[ +]

= SEIS 615 Assignment 1: Account Setup
Jason Baker <bake2352@stthomas.edu>
2.0, 8/10/2020

:sectnums!:

== Overview

You have three required tasks and one optional task to complete this week,
as well as the assigned readings. Don't wait until the end of the week to
begin working on these tasks!

* Sign up for a free GitHub.com account.
* Sign up for a free Slack account and optionally install software on your desktop and/or
mobile device.
* Sign up for an Amazon Web Services account.
* (Optional) Take a Git training online class.

:sectnums:
==  GitHub.com account

Sign up for a free GitHub account by going to https://github.com and clicking
the `Sign Up` button. You are welcome to use an existing personal GitHub account if have one. *Please e-mail me your GitHub username once you have an account setup.* Do not send me your GiHub password. Every assignment in this class is submitted using GitHub repositories.

== Slack account
Sign up for a free Slack account at https://ustseis615.slack.com/signup using
your @stthomas.edu email address. Slack is
a chat-based collaborative platform used by thousands of organizations. It is heavily
used in DevOps organizations.

You can access Slack using a web browser or you can download a desktop application
(https://slack.com/downloads). Slack is also available as an app for your mobile
device. This course doesn't teach you how to use Slack, but it's pretty easy
to figure out. Just go to the Slack website and click on the `Getting Started` link
to learn the basics.

We will use Slack as a group communication tool throughout the course. If you have a
question or encounter a problem while working with a tool, you should ask your
question on Slack first. Students that actively participate on Slack and assist
other students with issues may receive extra credit points.

Note that even though we will use Slack as a collaboration tool, students must
complete and submit their own work on assignments. Some of the exam questions
will relate to the assignments, and students that don't complete the assignments
on their own will have difficulty taking the exams.

== AWS account

We will use Amazon Web Services extensively throughout the course to learn how
to work with cloud-based infrastructure. You are required to setup an AWS account
to complete many of the assignments. You may use an existing school AWS
account for the class as long as it is associated with your UST email account. 
*You must provide a valid credit card when signing up for an AWS account*. Note, if you plan to use an existing AWS account which you used in a previous class, you must make sure that this account was *not* created as an AWS Educate Starter account because this account type will not work for our class. You would need to create a new AWS account in this case.

Amazon offers a _free_ tier of service for users with new accounts. This free tier
lasts for one year after the account is registered. This course makes every effort to stay within the free tier of service at AWS. However, there are times when your account will likely incur hourly charges. The free tier of service combined with educational credits should cover all of your expenses. *You are responsible for covering any additional expenses not covered by these credits.*

Go to http://aws.amazon.com/ and click on the `Sign In` link to sign up for a
new AWS account. You should use your @stthomas.edu email address when signing
up for the account. Also, you need to provide Amazon with a valid credit card during the account setup process. Choose the basic support option. The other support options are designed for businesses. We will provide AWS support to one another via the class Slack channel.

*Note, do not select the AWS Educate Starter Account option when signing up for an account.* If you select this option, you *will not* be able to complete all of the assignments in this course. 

Once your AWS account is setup, your instructor will e-mail you an educational credit code after the semester begins which you can apply to your account. In previous semesters AWS generously gave each student $100 worth of credit to work on assignments.

== Git training

Understanding how to use Git is essential in this course. Your experience and comfort-level working with Git can have a *major impact* on your grade. Online Git training provides a quick introduction to Git where you can
play with some of the basic commands. Students that have not used Git before
are *strongly encouraged* to take this training:

  https://www.learnenough.com/git-tutorial/getting_started

You can also learn how to use the GitHub website using free online training at these sites:
  
  https://try.github.io/
  https://www.codecademy.com/learn/learn-git
  https://learngitbranching.js.org
  https://www.atlassian.com/git

Please plan to invest additional learning time at the beginning of the course if you do not have experiencing working with Git or source control systems.
