:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Assignment 9: Code pipeline
Jason Baker <bake2352@stthomas.edu>
2.0, 7/20/2019

== Overview
A DevOps code pipeline helps to automate continuous delivery processes for software development organizations. Developers, testers, and operations staff depend on functioning pipelines to transform code changes into deployable software releases. While software developers are the primary users of a pipeline, IT operations professionals oftentimes have to maintain it.

In this week's assignment, you will build a code deployment pipeline using AWS CodePipeline, a continuous delivery tool. The pipeline will test, build, and deploy a very simple Python application.


== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Let's get that code pipeline flowing!

=== Setup the Python application

The first step in the assignment is to create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/assignment-invitations/874ccbb14cf1edafbdf104af22f7812f

Next, copy the files and directories from the following repository into your new classroom private repository:

  https://github.com/seis665/python-project

How should you do this? One possible method is to clone the `python-project` repository and the classroom repository to your system, copy the python-project repository contents to your classroom repository directory, and push the classroom repository directory files back to GitHub. 

=== Create a CloudFormation stack

You will use a CloudFormation template to launch a stack containing the software delivery pipeline and the infrastructure resources which will host a Python web application. You don't have to create this template from scratch. We launched a pipeline template during the hands-on portion of this week's lecture which built and deployed the Python application. You can use this template as a starting point:

  https://seis665.s3.amazonaws.com/app-codepipeline-template.json

As a quick reminder, the template will create the following resources:

* An AWS Virtual Private Cloud (VPC), two subnets in separate AZs including all the necessary routing tables and routes, and an Internet gateway.

* An Application Load Balancer which will listen for requests on port 80 and forward these requests to an auto-scaling group containing two EC2 instances (t3.micro).

* CodeBuild and CodePipeline resources required to build out a software delivery pipeline for the python-project repository you cloned above.

Your goal in this assignment is to enhance the pipeline currently defined in the template. 

-- The current pipeline has a stage called `Build` in which CodeDeploy performs unit testing and a build step to generate the Cascading Style Sheet (CSS) code. Let's separate these two steps into completely separate CodePipeline stages called `UnitTest` and `Build`. The `UnitTest` stage will use CodeDeploy to perform a unit test and the `Build` stage will build the application code (in this case the CSS part of the web application). Note that unit testing requires a Python environment and building requires a Nodejs environment.

-- It's common to lint our code before running unit tests. Linting is a form of static code analysis and it can catch many simple types of errors. Add a linting step to the `UnitTest` stage and run it before the unit test. You can lint the python application by running the command:

  flake8 app.py

If you encounter a linting error when triggering the pipeline, correct the code issue in the `app.py` script and try to trigger the pipeline again.

-- The current pipeline is not automatically triggered when your `python-project` repository is updated. Test this out by trying to update the `README.md` file in the repository. How come the pipeline isn't automatically triggering? We need to create a webhook resource in order for that to happen. Add an `AWS::CodePipeline::Webhook` resource to your CloudFormation template with the proper configuration to automate the pipeline trigger on repository code updates.




Congratulations! You've created the infrastructure required to build a code pipeline.


line should include the following named stages (highlighted in bold):



=== Save your work

Copy the CloudFormation template you modified for this assignment into this new repository and commit the code. 

=== Check your work

Here is what the contents of your git repository should look like before final submission:

====
&#x2523; Jenkinsfile +
&#x2517; console.txt
====

=== Terminate application environment

The last step in the assignment is to delete all the AWS resources created by the stack. You don't want to keep this stack running for a long time because the costs will accumulate.

Go to the CloudFormation dashboard, select your running stack, and choose the
delete option. Watch as CloudFormation deletes all the resources previously
created.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
