:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 615 Assignment 9: Code pipeline
Jason Baker <bake2352@stthomas.edu>
3.0, 11/7/2021

== Overview
A DevOps code pipeline helps to automate continuous delivery processes for software development organizations. Developers, testers, and operations staff depend on functioning pipelines to transform code changes into deployable software releases. While software developers are the primary users of a pipeline, IT operations professionals oftentimes have to maintain it.

In this week's assignment, you will build a code deployment pipeline using AWS CodePipeline, a continuous delivery tool. The pipeline will test, build, and deploy a very simple Python application.


== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Let's get that code pipeline flowing!

=== Setup the Python application

The first step in the assignment is to create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/a/rdHjH7DJ

When your classroom repository is setup, GitHub will automatically copy projects files into it from a template repository. 

=== Create a CloudFormation stack

You will use a CloudFormation template to launch a stack containing the software delivery pipeline and the infrastructure resources which will host a Python web application. You don't have to create this template from scratch. We launched a pipeline template during the hands-on portion of this week's lecture which built and deployed a Python application. You can use this template as a starting point:

  https://seis615.s3.amazonaws.com/app-codepipeline-template.yaml

As a quick reminder, the template will create the following resources:

* An AWS Virtual Private Cloud (VPC), two subnets in separate AZs including all the necessary routing tables and routes, and an Internet gateway.

* An Application Load Balancer which will listen for requests on port 80 and forward these requests to an auto-scaling group containing two EC2 instances (t2.micro).

* CodeBuild and CodePipeline resources required to build out a software delivery pipeline for the python-project repository you cloned above.

* CodePipeline will use the CodeDeploy service to deploy the python software artifacts to the EC2 instances.

When launching the template you will need to specify the location of the GitHub repository the pipeline will pull source code from. Note that this repository isn't technically owned by you. It belongs to an organization called `ustseis615` and therefore you must use `ustseis615` for the GithubUsername parameter, not your personal username. The GithubRepositoryName parameter also must reference your classroom repository name, for example: `assignment-9-code-pipeline-jasondbaker`. Finally, the GitHubAccessToken parameter value should be a GitHub personal access token (watch the lecture videos again if you don't remember how to create this).

Your goal in this assignment is to enhance the existing pipeline defined in the CloudFormation template. Specifically, you will need to make three changes:

1. Separate the current build stage into separate unit test and build stages.
2. Add linting to the unit test stage.
3. Modify the pipeline so that it is automatically triggered when the code repository is updated using a webhook.

=== Create a new unit test stage

CodePipeline uses multiple stages to define a software delivery process. The first stage (`Source`) retrieves the software code from GitHub. The second stage (`Build`) performs unit testing and a build on this software code. The third and final stage (`Deploy`) deploys the software code artifact to a set of EC2 instances.

The `Build` stage of the pipeline uses CodeBuild and a `buildspec.yml` file to perform unit testing and an application build. Let's separate the unit test and build steps in this stage into completely separate CodePipeline stages called `UnitTest` (the new second stage) and `Build` (now the third stage). Is this separation really necessary in this case? Not really, but it provides good practice for working with CodeBuild and CodePipeline resources.

We can reuse the existing CodeBuild resource in the pipeline but we need to employ some trickery using environment variables to do it. Each pipeline stage using CodeBuild will need to set an environment variable called `BUILD_TYPE`. The UnitTest stage should assign this variable the value `UNITTEST` and the Build stage should assign this variable the value `BUILD`. You can set this environment variable in the `Configuration` section of the stage. See the following CodePipeline documentation for more details:

  https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html

Now that the UnitTest and Build stages are passing an environment variable to CodeBuild, we need to modify the `buildspec.yml` file to make use of this environment variable. We want the UnitTest stage to run the unit test commands and the Build stage to run the build commands. Check out this example code snippet:

   pre_build:
    commands:
      - |
        set -e
        if [ "$BUILD_TYPE" = "UNITTEST" ]; then
          # run unittest commands
        fi
  build:
    commands:
      - |
        set -e
        if [ "$BUILD_TYPE" = "BUILD" ]; then
          # run build commands
        fi

In the example above, CodeBuild will run the commands in the unittest block if the `BUILD_TYPE` environment variable is equal to `UNITTEST` and the build commands if the variable is equal to `BUILD`. This pattern allows the CodePipeline stages to control which set of commands are executed by CodeBuild during a build. 

Here are some helpful documentation links that you might use for this part of the assignment:

  https://docs.aws.amazon.com/codepipeline/index.html
  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

=== Add linting to the unit test stage

Now that we have a new unit test stage we can expand it with some linting. Linting is a form of static code analysis and it can catch many simple types of errors. It's common to run code linting before running unit tests. Add a linting step to the `UnitTest` stage and run it before the unit test command (`pytest`). You can lint the python application by running the command:

  flake8 app.py

It's possible that the python application code will trigger a linting error. If you encounter a linting error (like error code `E302`) when running the pipeline, review the linting error message and correct the python code issue in the `app.py` script. The linting error message usually shows the line number and column position in the source code text file where the linting issue was found. 

Try to trigger the pipeline again (release change) to see if the linting issue was fixed. It may take you a few attempts to fix any linting issues. Once the pipeline runs all of the stages successfully, you should be able to access the application load balancer endpoint to view the deployed web application running in the deployment environment.

=== Automatically trigger the pipeline during code changes.

In this week's lecture video you learned that GitHub code changes can automatically trigger a CodeBuild project. This is a really common pattern in software delivery pipelines and an essential part of continuous integration. Every change a developer commits to a repository results in a build and potential application deployment. In this case we are simulating a deployment to a test environment. 

A pipeline managed by CodePipeline can be triggered by changes to a GitHub repository using a webhook. GitHub can initiate a webhook when a commit is made to the repository. What is a webhook? It's basically just a special web request sent to a specified API endpoint -- in this case an endpoint hosted by AWS. 

Test out the webhook by trying to update the `README.md` file in the repository. Is your AWS pipeline automatically triggering? If so, congratulations you have completed the assignment!


=== Save your work

Copy the CloudFormation template you modified for this assignment into this new repository and commit the code. 

=== Check your work

Your repository will contain all of the application files created by the repository template. Additionally, your git repository should contain the following files before final submission:

====
&#x2523; app-codepipeline-template.json +
&#x2517; app.py +
&#x2517; appspec.yml +
&#x2517; buildspec.yml
====

=== Terminate application environment

The last step in the assignment is to delete all the AWS resources created by the stack. You don't want to keep this stack running for a long time because the costs will accumulate. Note, you will need to empty the S3 artifact bucket before deleting the stack because CloudFormation cannot automatically delete an S3 bucket which contains objects.

Go to the CloudFormation dashboard, select your running stack, and choose the
delete option. Watch as CloudFormation deletes all the resources previously
created.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
