:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Assignment 9: Code pipeline
Jason Baker <bake2352@stthomas.edu>
2.0, 7/20/2019

== Overview
A DevOps code pipeline helps to automate continuous delivery processes for software development organizations. Developers, testers, and operations staff depend on functioning pipelines to transform code changes into deployable software releases. While software developers are the primary users of a pipeline, IT operations professionals oftentimes have to maintain it.

In this week's assignment, you will build a code deployment pipeline using AWS CodePipeline, a continuous delivery tool. The pipeline will test, build, and deploy a very simple Python application.


== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Let's get that code pipeline flowing!

=== Setup the Python application

The first step in the assignment is to create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/assignment-invitations/874ccbb14cf1edafbdf104af22f7812f

When your classroom repository is setup, GitHub will automatically copy projects files into it from a template repository. 

=== Create a CloudFormation stack

You will use a CloudFormation template to launch a stack containing the software delivery pipeline and the infrastructure resources which will host a Python web application. You don't have to create this template from scratch. We launched a pipeline template during the hands-on portion of this week's lecture which built and deployed a Python application. You can use this template as a starting point:

  https://seis665.s3.amazonaws.com/app-codepipeline-template.json

As a quick reminder, the template will create the following resources:

* An AWS Virtual Private Cloud (VPC), two subnets in separate AZs including all the necessary routing tables and routes, and an Internet gateway.

* An Application Load Balancer which will listen for requests on port 80 and forward these requests to an auto-scaling group containing two EC2 instances (t3.micro).

* CodeBuild and CodePipeline resources required to build out a software delivery pipeline for the python-project repository you cloned above.

* CodePipeline will use the CodeDeploy service to deploy the python software artifacts to the EC2 instances.

Your goal in this assignment is to enhance the existing pipeline defined in the CloudFormation template. Specifically, you will need to make three changes:

1. Separate the current build stage into separate unit test and build stages.
2. Add linting to the unit test stage.
3. Modify the pipeline so that it is automatically triggered when the code repository is updated using a webhook.

=== Create a new unit test stage

CodePipeline uses multiple stages to define a software delivery process. The first stage retrieves the software code from GitHub. The second stage performs unit testing and a build on this software code. The third and final stage deploys the software code artifact to a set of EC2 instances.

The current pipeline has a stage called `Build` which uses CodeBuild to perform unit testing and an application build. Let's separate the unit test and build steps in this stage into completely separate CodePipeline stages called `UnitTest` and `Build`. The `UnitTest` stage will use CodeBuild to perform a unit test, and the `Build` stage will use CodeBuild to build the application code (in this case the CSS part of the web application). Note that unit testing requires a Python environment and building requires a Nodejs environment, so you should only specify the appropriate environments for their related tasks.

Here are some helpful documentation links that you might use for this part of the assignment:

  https://docs.aws.amazon.com/codepipeline/index.html
  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

=== Add linting to the unit test stage

Now that we have a new unit test stage we can expand it with some linting. Linting is a form of static code analysis and it can catch many simple types of errors. It's common to run code linting before running unit tests. Add a linting step to the `UnitTest` stage and run it before the unit test. You can lint the python application by running the command:

  flake8 app.py

It's possible that the python application code will trigger a linting error. If you encounter a linting error when running the pipeline, review the linting error message and correct the python code issue in the `app.py` script. Try to trigger the pipeline again to see if the linting issue was fixed.

=== Automatically trigger the pipeline during code changes.

In this week's lecture video you saw how a CodeBuild process could automatically be triggered by code changes in the GitHub repository. This is a really common pattern in software delivery pipelines and an essential part of continuous integration. Every change a developer commits to a repository results in a build and potential application deployment. In this case we are simulating a deployment to a test environment. 

A pipeline managed by CodePipeline can also be triggered by changes to a GitHub repository using a webhook. This is setup a little differently than CodeBuild, but the results are the same. Check out the AWS::CodePipeline::Webhook CloudFormation resource documentation at:

  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-webhook.html

Create a new webhook resource in the template and update your stack. Test it out by trying to update the `README.md` file in the repository. Is your pipeline automatically triggering? If so, congratulations you have completed the assignment!


=== Save your work

Copy the CloudFormation template you modified for this assignment into this new repository and commit the code. 

=== Check your work

Here is what the contents of your git repository should look like before final submission:

====
&#x2523; app-codepipeline-template.json +
&#x2517; app.py +
&#x2517; appspec.yml +
&#x2517; buildspec.yml
====

=== Terminate application environment

The last step in the assignment is to delete all the AWS resources created by the stack. You don't want to keep this stack running for a long time because the costs will accumulate. Note, you will need to empty the S3 artifact bucket before deleting the stack because CloudFormation cannot automatically delete an S3 bucket which contains objects.

Go to the CloudFormation dashboard, select your running stack, and choose the
delete option. Watch as CloudFormation deletes all the resources previously
created.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
