:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Assignment 8: CloudFormation
Jason Baker <bake2352@stthomas.edu>
1.2, 4/1/2017

== Overview
In our class we discussed how IT professionals now design and provision infrastructure using
code -- a concept known as Infrastructure as Code. The AWS CloudFormation
service allows you to define cloud infrastructure using JSON template files.
These template files create resource stacks in AWS.

In this week's assignment, you will use AWS CloudFormation to create a
basic stack. Your stack will expand the stack design that was created during
the hands-on portion of the class. The easiest way to start creating your stack is by using
the CloudFormation Designer tool, although you will need to use a code editor as well.

You will learn how code can simplify and ensure the repeatability of infrastructure
deployments. Some students note that it takes more effort to create infrastructure using code versus manually creating infrastructure using a web console. That's probably true initially, especially when you are less familiar with infrastructure as code techniques. However, remember the ultimate goal is to automate the building of infrastructure. Once you spend the time writing code to build out an infrastructure environment, you can generate copies of that environment using your code within minutes. That's the power of code and automation!

== Requirements

You need to have a personal AWS account and GitHub account for this assignment.

== The assignment

Your first stack awaits! Let's go.

=== Download CloudFormation template

This week's assignment isn't as prescriptive as some of the previous assignments.
You will likely need to experiment with the CloudFormation Designer and template
code a bit to build the required solution. You can review the class powerpoint
presentation, AWS CloudFormation documentation, and YouTube resources if you
need help to figure out how to configure a resource.

You may use the following template as a starting point for the assignment:

====
https://s3.amazonaws.com/seis665/BasicWebserverInVPC.json
====

Here's the background story for this assignment: The engineering manager at your office came to you and asked
if you could build a new CloudFormation stack template called `corpweb.json` for the development team. The stack must have
two Amazon Linux EC2 instances located behind an Elastic Load Balancer. The
load balancer must handle incoming requests on port 80 and send those to the
EC2 instances on port 80. Additionally, the two instances need to be members of a security group which
allows incoming traffic on ports 22 and 80.

The engineering manager would like users to be able to provide two *input parameters* when launching the stack:

  * A parameter called *InstanceType* that defines the instance type for the instances.
      ** The allowable type must be one of the following: t2.micro or t2.small
  * A parameter called *KeyPair* that specifies the server key-pair name for the EC2 instances.

Also, she would like you to create an output called *URL* that displays the load balancer dns name
after the stack is launched.

The stack template should create the following resources:

  * A new VPC called: *EngineeringVPC*
    ** CIDR block should be: 10.0.0.0/16
    ** The VPC should enable DNS hostnames.
    ** The VPC should have one subnet called: *PublicSubnet*
        *** Subnet has a CIDR block of 10.0.0.0/24
    ** The subnet should be able to route data out to the Internet.
  * Two EC2 instances named (tagged) *web1* and *web2* in the PublicSubnet.
    ** Instance type: <use input parameter>
    ** Use this public AMI image: *ami-3ea13f29*
    ** Server key-pair: <use input parameter>

  * A security group named *WebserversSG* in the VPC.
    ** Allow incoming requests on port 22 from 0.0.0.0/0
    ** Allow incoming requests on port 80 from 0.0.0.0/0
  * A load balancer (classic v1) named *EngineeringLB*
    ** Load balance incoming requests on port 80 and send to instance port 80 using the http protocol.
    ** Load balancer health check via http on port 80 to the "/" url location.

[NOTE]
====
The names of the resources you configure in your stack template must *exactly* match the values above. The names are case-sensitive, so a resource with the name of "Web1" is not the same as "web1". You will lose points on this assignment if your resource names do not match the expected names. You should always double-check your work.
====

=== Launch the stack

Once you have created and validated your template, save it to your local file
system. Next launch your new stack, called *WebserversDev*, in us-east-1 and provide the proper input parameters. Watch as AWS CloudFormation goes through the
build process and creates the resources defined in the template. It will take a few minutes for CloudFormation to build the stack
resources.

It's likely that your stack launch will fail to complete the first time you try
to launch the stack. Take a look at the events associated with the stack to try
to determine which resource CloudFormation failed to create properly. You will
see an error message describing why the resource failed. Oftentimes a resource
will not get built because the one of the resource properties is missing or is
incorrect. Try to fix the error in the template and launch the stack again.

When you see that the stack launch completed and the EC2 instances are running, go ahead and terminal into
one of the instances to confirm that you can access the server. Next, look at
the output value from the CloudFormation stack to determine the DNS address
for the load balancer that was created. Enter this DNS address into your
web browser to confirm that it is distributing requests across the instances
properly.

=== Check your work

Here is what the contents of your git repository should look like before final submission:

====
&#x2523; corpweb.json +
====

=== Save your work

Create a new GitHub Classroom repository by clicking on this link: https://classroom.github.com/assignment-invitations/4bb37342c50150f66bef6b83443c44fc

Commit your `corpweb.json` stack template file to this repository. You could create a new Git repository on your local machine, commit the template file to it, and then push the local repository up to GitHub. Or, you could use the GitHub web console to create a new repository and upload your template file to it. The
latter method is probably a little quicker for this assignment.

[WARNING]
====
You are responsible for ensuring that the corpweb.json template file you commit to your repository actually works on AWS CloudFormation. In the past, some students have used text editors which made small changes to the template when it was saved to disk and committed to the git repository. The result is that the template no longer worked properly on CloudFormation and the students' grades were negatively impacted. *You should strongly consider testing the template after you commit it to the git repository to ensure that it still works.*
====

=== Terminate application environment

The last step in the assignment is to delete all the AWS services you created.
Go to the CloudFormation dashboard, select your running stack, and choose the
delete option. Watch as CloudFormation deletes all the resources previously
created.

== Submitting your assignment
I will review your published work on GitHub after the homework due date.
