---
- hosts: localhost
  become: yes
  
  tasks:
  
  - name: install linux security updates
    yum:
      security: yes
      state: latest

  - name: install boto3
    shell: |
      pip3 install boto3==1.20.10

  - name: install base packages
    yum:
      name: [
        'git', 
        'tar',
        'jq',
        'python3-pip',
        'python3',
        'unzip',
        'wget',
        'yum-utils',
        'zip'
      ]

  - name: install docker
    block:
      - name: install docker service
        shell: |
          amazon-linux-extras install docker
      - name: start docker service at boot
        service:
          name: docker
          enabled: yes
  
  - name: give ssm-user access to docker cmds
    user:
      name: ssm-user
      shell: /bin/bash
      append: yes
      groups: docker

  - name: set up sudoers configuration
    copy:
      src: /opt/ansible/files/ssm-agent-users
      dest: /etc/sudoers.d/ssm-agent-users
      owner: root
      group: root
      mode: 0440
  
  - name: install docker compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '0755'
