pipeline {
  agent none

  environment {
      MAJOR_VERSION = 1
  }

  stages {

    stage('Unit Tests') {
      agent {
        label 'apache'
      }
      steps {
        sh "env | sort"
        sh 'ant -f test.xml -v'
        junit 'reports/result.xml'
      }
    }
    stage('build') {
      agent {
        label 'apache'
      }
      steps {
        sh 'ant -f build.xml -v'
      }
      post {
        success {
          archiveArtifacts artifacts: 'dist/*.jar', fingerprint: true
        }
      }
    }
  }
}
