:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Week 6 Project: Infrastructure Pipeline
Jason Baker <bake2352@stthomas.edu>
1.0, 8/15/2018

== Overview
Create a very basic infrastructure pipeline using a Jenkins CI/CD system.

== Requirements

  * AWS account.
  * SSH terminal application.


== The project

Let's get started!

=== Launch a CloudFormation template.

Open up the CloudFormation web console and create a new stack by specifying the following S3 URL:

  https://s3.amazonaws.com/seis665/jenkins-cf.json


The template will create a stack containing a Jenkins server environment:

* An AWS Virtual Private Cloud (VPC) including a subnet, routing table, routes, an Internet gateway, and a security group.

* A Jenkins server.

* Two Jenkins worker nodes.

On the stack *Specify Details* page, take note of the following input parameters which you haven't encountered
before:

1. In *JenkinsUsername*, leave the value set to `admin`.
2. In *JenkinsPassword*, set the value to your desired password.
3. In *YourIp*, type in the value of your workstation's IP address in CIDR notation (use checkip.amazonaws.com to verify).

It will take a few minutes for CloudFormation to create the AWS resources for you. You can watch the progress messages on the *Events* tab in 
the console. When the stack has been created, you will see a CREATE_COMPLETE message in the *Status* column of the console and on the 
*Overview* tab.


=== Infrastructure

Look at the stack `Outputs` tab to get the IP address of the Jenkins server. You can log into the server using
the following web address (Jenkins runs on port 8080:

    http://<jenkins server IP>:8080

Log into the Jenkins server with your username and password. Once you have logged into the server, create a 
new pipeline project by clicking on `New Item`, typing in the name of your project (`infrastructure`),  
selecting the Pipeline item, and clicking `Ok`. 

Jenkins will display the configuration settings for your new pipeline project. We're mostly interested in the
`Pipeline` section at the bottom of the configuration page. You will create a pipeline by entering code into
the `script` textbox.

Here is an example script you can enter into the script field:

....
node ("linux") {
    stage ("GetInstances") {
        
        sh "aws ec2 describe-instances --region us-east-1"
    }
    
}
....

The script describes the steps the pipeline will run when it is built. A pipeline is partitioned into multiple stages, denoted by the `stage` object, and each stage can contain multiple steps. For example, the pipeline above has a single stage called `GetInstances`. Inside this stage you will find a single step where Jenkins executes a shell command using the `sh` module. Jenkins runs this command on a worker node. 

Enter this script and click the `Save` button. Next, click the `Build Now` link to build your project. Note that
we use the term _build_ loosely in this context. Typically a build involves some type of code linking and compilation.
Here a build means some sort of process which potentially produces an output artifact.

Each time you run a build it creates a build number and displays it in the Build History. Click on the most recent
build number. Next, click on the `Console Output` to view the output from your pipeline project.

What are you seeing here? Jenkins is simply running a shell command (using the `sh` commmand) and logging the output from the command. 
Jenkins isn't running this command on the Jenkins server, it's running on the slave node (named `linux`). The Jenkins server is 
acting as a master scheduler coordinating the running of projects like your pipeline.  

=== Extend pipeline

When we build infrastructure pipelines, we create each stage of the pipeline one step at a time. Let's modify the previous pipeline you created to add another stage. Add an additional pipeline stage which launches an EC2 instance into your account. The EC2 instance should have the following characteristics:

    * Use the latest Amazon Linux 2 AMI 
    * t2.micro instance type
    * Your EC2 key pair name
    * A valid security group ID associated with your default VPC
    * A valid subnet ID associated with your default VPC

An example `aws` CLI command to launch a new EC2 instance looks like:

    aws ec2 run-instances --image-id ami-287dnf7 --count 1 --instance-type t2.micro --key-name seis665 --security-group-ids sg-7edf3108 --subnet-id subnet-0bbd366e --region us-east-1

Note, this example won't work in your pipeline and you will need to modify it for your environment. For example, several of the parameter values like the security group will need to be changed.

Here's an example of how you might begin to extend the existing pipeline:

....
node ("linux") {
    stage ("GetInstances") {
        
        sh "aws ec2 describe-instances --region us-east-1"
    }
    
    stage ("CreateInstance") {
        // TODO
        
    }
    
}
....

=== Extra superfabulous task (optional)

Let's add two more steps to the second stage of your pipeline to: 1) verify that the EC2 instance created in the second stage is running and 2) terminate the new EC2 instance. This is a pretty common step in an infrastructure pipeline. Oftentimes we will create a resource, wait for the resource to be created, and then test it.

You will need two things to complete this task. The EC2 instance ID created by the AWS `run-instances` command. The sh command can be modified to return an output value which is assigned to a variable. For example:

    def output = sh returnStdout: true, script: 'a command you want to run'

Many AWS CLI commands respond with some sort of output in the JSON data format. The `jq` command (https://stedolan.github.io/jq/) is available on the build node to parse this JSON output. For example:

    def output = sh returnStdout: true, script: 'cat foo.json | jq .'
    
You will have to figure out how to setup the `jq` command properly to get the instance ID for the new EC2 instance that was created. Once the pipeline launches the instance, you need to add a waiter. The purpose of a waiter is to literally wait until a specified process completes. In this case, you want the pipeline to wait until the EC2 instance is running. Hint, check out the `aws ec2 wait` command. The pipeline is working correctly if the waiter completes without generating an error.

Finally, add a step to terminate the new EC2 instance. 


=== Show me your work

Please show me your pipeline code.

=== Terminate AWS resources

Remember to terminate all the resources created in this project, including the EC2 instance created by your
pipeline.
