:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Week 3 Project: AWS
Jason Baker <bake2352@stthomas.edu>
1.0, 8/15/2018

== Overview
Setup AWS S3 and EC2 resources.

== Requirements

  * AWS account.
  * SSH terminal application.


== The project

Let's get started!

=== Create S3 bucket

Create an S3 bucket in the us-east-1 region and upload an image into it. You can select any sort of image you would like. Configure S3 to store the image on Reduced Redundancy storage and in an encrypted format.


=== Create an EC2 instance

Create an EC2 instance with the following properties:

* t2.medium instance size
* AWS Linux AMI
* us-east-1 region
* 10GB root volume storage size

SSH into the new EC2 instance and update all the system packages. Install the Nginx webserver software on the instance.

=== Extra super funtastic task (optional)

Write a shell script called `server-properties.sh` located in your user home directory which queries the instance meta-data endpoint to retrieve the public IP address and security group of the instance. Write these values to a file called `server-data.txt` in the home directory.

=== Create an AMI

Create an AMI based off the new EC2 instance you created above. Once the AMI is built, launch a new EC2 instance using your new AMI. The properties of the EC2 instance can be similar to the ones above.


=== Show me your work

Please show me your new instance built off the custom AMI and your S3 bucket.

=== Terminate server

Remember to terminate your EC2 instances and remove your S3 bucket once you have completed the project.
