:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Week 10 Project: Software Delivery Pipeline
Jason Baker <bake2352@stthomas.edu>
2.0, 7/21/2019

== Overview
Create an automated software delivery pipeline using CodeCommit, CodeBuild, CodeDeploy and CodePipeline.

== Requirements

  * AWS account.
  * SSH terminal application.


== The project

Let's get started!


=== Java project setup

During one of the lecture hands-on segments we used GitHub and AWS CodeBuild to generate a build artifact for a very simple Java application. Let's expand on that exercise a bit in this class project. Instead of hosting the application source code in GitHub let's try using AWS CodeCommit, Amazon's managed git repository service. Also, let's use AWS CodePipeline to manage the build process.

Okay, let's start begin building the pipeline!

=== Create a CloudFormation template

We always create infrastructure resources using code whenever possible and code repositories are no different. You should build a CloudFormation template to create all of the resources for this project including an S3 artifact bucket,  CodeCommit repository, CodeBuild project, and CodePipeline pipeline. Instead of starting from scratch, you can use the following template as a starting point:

  https://seis665.s3.amazonaws.com/app-codebuild-template.json

=== Create a CodeCommit repository

One of the first resources you need to add to the CloudFormation template is a CodeCommit repository. You will use this as a git repository to host the Java application source code. You can use the following documentation to understand how to configure the repository resource:

  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codecommit-repository.html

Here are a couple helpful notes:

  * Give the repository a simple name like `java-project`
  * A zipfile containing the source code for the Java project is located in S3. You can configure CloudFormation to automatically copy this source code into the repository during creation.
      https://seis665.s3.amazonaws.com/java-project.zip

=== Modify the CodeBuild project

The CodeBuild project resource in the template you copied was configured to use a GitHub repository, not CodeCommit. You will need to modify this resource to work properly with CodeCommit. Here is CodeBuild resource CloudFormation documentation:

  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-source

There are a number of changes you need to make to the template to get the CodeBuild project connected to CodeCommit. Here are some hints:

  * Since we are no longer using GitHub there's no reason to pass a projectUrl parameter into the template. We can pass the CodeCommit repository information to the CodeBuild project because both resources are defined in the same template.
  * The `Source` property in the CodeBuild project tells the CodeBuild service where to find the application source code.
  * The `ReportBuildStatus` property is not supported by CodeBuild projects using CodeCommit repositories.
  * CodeCommit doesn't use webhooks to trigger CodeBuild projects.
  * The CodePipeline project resource uses a custom IAM role to access other AWS services and resources. For example, the role allows the project to retrieve and store objects in an S3 artifact bucket. The role does not currently allow CodePipeline to pull source code from a CodeCommit repository. You can update the project role to allow this by adding the following policy statement to the role:


  {
    "Sid": "CodeCommitPolicy",
    "Effect": "Allow",
    "Action": [
      "codecommit:GitPull"
    ],
    "Resource": [
      "*"
    ]
  }


Once you see a successful build and a new artifact uploaded into the S3 artifact bucket you are ready to continue working on the next stage of the project. If your build doesn't work, make note of the error message and try to figure out what is going on using your favorite search engine or troubleshooting sites like StackOverflow.

=== Test your template changes

Now is a good time to test the changes you have made to the CloudFormation template. Create a new stack using your template and wait for it to create all of the resources. Access the CodeCommit web console to verify that a `java-project` repository exists and it contains a set of application source files. One of those files should be the `buildspec.yml` file.

Next, go to the CodeBuild web console and verify that a build project exists. It should be configured to use your `java-project` repository as a build source. Go ahead and start a build to test the build process. Take a look at the build logs as the project is building. 

=== Add a pipeline resource



=== Super-sized task (optional)

-- CodePipeline will not trigger a new build by default. Add a webhook to enable this capability..


=== Show me your work

Please show me your CloudFormation template code and successful CodePipeline execution.

=== Terminate AWS resources

Remember to terminate all the resources created in this project, including the EC2 instance created by your
pipeline.
