:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 615 Week 13 Project: AWS Fargate
Jason Baker <bake2352@stthomas.edu>
3.0, 12/4/2021

== Overview
Use the AWS ECS and Fargate to create a container cluster and launch the Wordpress application into it.

== Requirements

  * AWS account

== The project

Let's get started!

=== Setup an ECS Service-Linked Role

You will need to setup a special Service-Linked Role for ECS if you have never used the ECS service before. The easiest way to do this is to access the AWS ECS web console and click on the `Get Started` button. Clicking this button will take you to a wizard where you can launch a sample task called `first-run-task-definition`. The wizard process creates the necessary role in the background for you.

Another way to create the role is to access the AWS CLI and run the following command:

  aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com

=== Create a CloudFormation template

Download this CloudFormation template to your workstation:

  https://s3.amazonaws.com/seis615/pets-discovery-wp-project.yaml

We used a similar version of this template to create an ECS/Fargate cluster in this last week's lecture. This version includes a couple additional configuration items. It creates the following resources:

    * A VPC containing subnets and Internet Gateway
    * An ECS cluster with a couple services and tasks
    * An application load balancer
    * A Cloud Map service namespace
    * Several parameters 

We need to modify this template to run the Wordpress application. Remember Wordpress? Of course you do. This is the fourth and final time we will use it in this course.

Rename the downloaded file `wordpress-template.yaml`. Now modify the `wordpress-template.yaml` template code in your code editor to launch a Wordpress environment. There are a number of change you will need to make to the template.

    * Change the name of the ECS cluster to `WordpressCluster`.
    * Create a web service task using the `ghcr.io/ustseis615/wordpress` Docker image (see: https://hub.docker.com/_/wordpress/)
        ** The Wordpress service in the container is listening on port 80.
        ** Configure the service to run 3 web service tasks.
        ** Modify the webserver security group to allow incoming access on port 80.
        
        ** Setup the following web task environment variables:
            *** `WORDPRESS_DB_HOST` with a value `db.service.wordpress:3306`.
            *** `WORDPRESS_DB_USER` with a value referencing parameter mysqlUser.
            *** `WORDPRESS_DB_PASSWORD` with a value referencing parameter mysqlPassword.
            *** `WORDPRESS_DB_NAME` with a value referencing parameter mysqlDatabase.

    * Create a db service task using the `ghcr.io/ustseis615/mariadb` Docker image (see: https://hub.docker.com/_/mariadb)
        ** The MariaDB container should listen on port 3306.
        ** Modify the database security group to allow access from the web security group on port 3306.
        ** Setup the following database task environment variables:
            *** `MYSQL_ROOT_PASSWORD` with a value referencing parameter mysqlRootPassword.
            *** `MYSQL_DATABASE` with a value referencing parameter mysqlDatabase.
            *** `MYSQL_USER` with a value referencing parameter mysqlUser.
            *** `MYSQL_PASSWORD` with a value referencing parameter mysqlPassword.
    
    * Modify the application load balancer:
        ** The load balancer target group should forward requests to port 80.
        ** Application load balancer health check endpoint is `/`.

    * Modify the Cloud Map service discovery namespace to use the name `service.wordpress`.


=== Launch Wordpress cluster

Create a stack called `wordpress` using your new CloudFormation template. You can select a reasonable set of passwords for the database service (the passwords can be the same). We need to provide a bunch of values for the salt parameters. What is a salt? It's a set of randomly generated values which are used to securely hash passwords. Our template will launch 3 Wordpress webservers and we need to make sure that all three Wordpress configuration files are using the same password salt. If we don't do this, we won't be able to log into the load balanced Wordpress application properly.

What sale values should we use? The salt parameter values are populated with a set of values that will work for this project. Warning: you should never use these values in a real production Wordpress site. If you ignore this warning your Wordpress site will be hacked. You have been warned.

The stack will take about 10 minutes to launch.

Test out the Wordpress application by going to the ELB endpoint address in your web browser. If you see the standard Wordpress installation page then congratulations! Here are some troubleshooting hints if you encounter an error message.

    * Check the load balancer target group to see if the load balancer health check is failing.
    * Go to the ECS web console and look at the task logs. Sometimes the log files can provide helpful troubleshooting info. For example, maybe the Wordpress containers can't communicate properly with the MariaDB container.
    * You can stop the database task to clear the database. The cluster will automatically start a fresh database server for you.

Is this Wordpress template production worthy? No. It has two big problems. First, we are persisting data in a database service running inside a container. The data will disappear when the container goes away. Using something like RDS would be a much better idea. Second, data uploads are stored on each individual web container. We would need to install something like a Wordpress S3 plugin to handle data uploads.

=== Cluster Hero task (optional)

Replace the MariaDB Fargate container with a Serverless Aurora Database running a MySql engine.

=== Show me your work

Please show me your running Wordpress application.

=== Terminate AWS resources

Remember to terminate the CloudFormation stack.
