:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Week 3 Project: AWS
Jason Baker <bake2352@stthomas.edu>
1.0, 9/25/2018

== Overview
Setup AWS S3 and EC2 resources.

== Requirements

  * AWS account.
  * SSH terminal application.


== The project

Let's get started!

=== Create an S3 bucket

Create an S3 bucket in the us-east-1 region using whatever name you like. Create a prefix (folder) in the bucket called `images` and upload an image  file into it. You can select any sort of image you would like and you may have to download one from the Internet if nescessary. Configure S3 to store the image on Reduced Redundancy storage and in an encrypted (AES-256) format.


=== Create an EC2 instance

Create an EC2 instance called `webtemplate` with the following properties:

* t2.micro instance size
* AWS Linux 2 AMI
* us-east-1 region
* 10GB root volume storage size
* A `MyWebserver` security group with the following rules:

** Allow access to the instance from the Internet via SSH (port 22) and HTTP (port 80)

You might notice after creating your security group that AWS adds an additional source to your rules with a funny looking syntax: `::/0`. This is the IPv6 (Internet Protocol version 6) representation of all the network addresses on the Internet. There's no need to remove or change this source.

SSH into the new EC2 instance and update all the system packages (review previous lecture if you don't remember how to do this). Install the Nginx webserver software on the instance. Access the public IP address of the instance from a web browser to verify that the Nginx webserver is running properly.

=== Create an AMI and New Instance

Create an AMI based off the new EC2 instance you created above. Once the AMI is built, launch a new EC2 instance called `web1` using your new AMI. The properties of the new EC2 instance should be similar to the previous instance.

=== Create API Server

Create a second EC2 instance called `apiserver` using the new AMI with the following properties: 

* t2.micro instance size
* AWS Linux 2 AMI
* us-east-1 region
* 10GB root volume storage size
* MyAPIService security group with the following rules:

** Allow access to the instance from MyWebserver security group via SSH (port 22), HTTP (port 80), and HTTPS (443).

=== Extra super funtastic task (optional)

Write a shell script called `server-properties.sh` located in your user home directory which queries the instance meta-data endpoint to retrieve the public IP address and security group of the instance. Write these values to a file called `server-data.txt` in the home directory. Upload this file into the S3 bucket you created earlier in this exercise.

Hint: You can use the `aws s3 cp` command and a set of API credentials to copy files to S3.


=== Show me your work

Please show me your new instances built off the custom AMI and your S3 bucket.

=== Terminate servers

Remember to terminate your EC2 instances and remove your S3 bucket once you have completed the project. You cannot delete S3 buckets that contain objects. You must delete all the bucket objects or empty the bucket first.
