:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 665 Week 8 Project: Infrastructure Pipeline
Jason Baker <bake2352@stthomas.edu>
1.0, 3/18/2018

== Overview
Create a very basic infrastructure pipeline using a Jenkins CI/CD system.

== Requirements

  * AWS account.
  * SSH terminal application.


== The project

Let's get started!

=== Launch a CloudFormation template.

Open up the CloudFormation web console and create a new stack by specifying the following S3 URL:

  https://s3.amazonaws.com/seis665/jenkins-cf.json


The template will create a stack containing a Jenkins server environment:

* An AWS Virtual Private Cloud (VPC) including a subnet, routing table, routes, an Internet gateway, and a security group.

* A Jenkins server.

* A Jenkins slave node.

On the stack *Specify Details* page, take note of the following input parameters which you haven't encountered
before:

1. In *JenkinsUsername*, leave the value set to `admin`.
2. In *JenkinsPassword*, set the value to your desired password.

It will take a few minutes for CloudFormation to create the AWS resources for you. You can watch the progress messages on the *Events* tab in 
the console. When the stack has been created, you will see a CREATE_COMPLETE message in the *Status* column of the console and on the 
*Overview* tab.


=== Infrastructure

Look at the stack `Outputs` tab to get the IP address of the Jenkins server. You can log into the server using
the following web address (Jenkins runs on port 8080:

    http://<jenkins server IP>:8080

Log into the Jenkins server with your username and password. Once you have logged into the server, create a 
new pipeline project by clicking on `New Item`, typing in the name of your project (`infrastructure`),  
selecting the Pipeline item, and clicking `Ok`. 

Jenkins will display the configuration settings for your new pipeline project. We're mostly interested in the
`Pipeline` section at the bottom of the configuration page. You will create a pipeline by entering code into
the `script` textbox.

Here is an example script you can enter into the script field:

....
node ("linux") {
    stage ("GetInstances") {
        
        sh "aws ec2 describe-instances --region us-east-1"
    }
    
}
....

Enter this script and click the `Save` button. Next, click the `Build Now` link to build your project. Note that
we use the term _build_ loosely in this context. Typically a build involves some type of code linking and compilation.
Here a build means some sort of process which potentially produces an output artifact.

Each time you run a build it creates a build number and displays it in the Build History. Click on the most recent
build number. Next, click on the `Console Output` to view the output from your pipeline project.

What are you seeing here? Jenkins is simply running a shell command (using the `sh` commmand) and logging the output from the command. 
Jenkins isn't running this command on the Jenkins server, it's running on the slave node (named `linux`). The Jenkins server is 
acting as a master scheduler coordinating the running of projects like your pipeline.  

=== Extend pipeline

When we build infrastructure pipelines, we create each stage of the pipeline one step at a time. Create an
additional pipeline stage which launches a new EC2 instance in your account. The EC2 instance should have the
following characteristics:

    * Use the latest Amazon Linux AMI 
    * t2.micro instance type
    * Your EC2 key pair name
    * A valid security group ID associated with your default VPC
    * A valid subnet ID associated with your default VPC

An example `aws` CLI command to launch a new EC2 instance looks like:

    aws ec2 run-instances --image-id ami-287dnf7 --count 1 --instance-type t2.micro --key-name seis665 --security-group-ids sg-7edf3108 --subnet-id subnet-0bbd366e --region us-east-1

Note, this example won't work in your pipeline and you will need to modify it for your environment.

Here's some pipeline code to get you started:

....
node ("linux") {
    stage ("GetInstances") {
        
        sh "aws ec2 describe-instances --region us-east-1"
    }
    
    stage ("CreateInstance") {
        // TODO
        
    }
    
}
....

=== Extra superfabulous task (optional)

Add a third stage to your pipeline which verifies that the EC2 instance created by the second stage is running.

You will need two things to complete this task. The EC2 instance ID created by the AWS `run-instances` command. The sh command can return an output value 
which is assigned to a variable. The AWS CLI is returning output using JSON. The `jq` command (https://stedolan.github.io/jq/) is available on 
the build node to parse the JSON output. Here's an example of how to assign a shell command output to a variable:

    def output = sh returnStdout: true, script: 'aws ec2 describe-instances | jq .'

Once the pipeline launches the instance, you need to add a waiter. The purpose of a waiter is to 
literally wait until a specified process completes. In this case, you want the pipeline to wait until
the EC2 instance is running. Hint, check out the `aws ec2 wait` command.


=== Show me your work

Please show me your pipeline code.

=== Terminate AWS resources

Remember to terminate all the resources created in this project, including the EC2 instance created by your
pipeline.