:doctype: article
:blank: pass:[ +]

:sectnums!:

= SEIS 615 Week 11 Project: Docker
Jason Baker <bake2352@stthomas.edu>
3.0, 8/10/2021

== Overview
Create a Docker image using a Dockerfile.

== Requirements

  * AWS account.

== The project

Let's get started!

=== Build a Docker server

The first step in the project is to build a Docker server running on EC2 using the following CloudFormation template:

  https://s3.amazonaws.com/seis615/docker-single-server.yaml

Launch the template to create a new stack. Shell into the new EC2 instance and run the following command:

  docker --version

The system should respond with the docker client version. Something like:

  Docker version 20.10.7, build f0df350

=== Working with containers

Let's start by getting comfortable with the Docker command line. How about a Hello World application? Type in the following command:

  docker run busybox echo hello world

The system should respond back with a bunch of output text including the words `hello world`. What is happening here? Docker created a small container using the `busybox` image, executed a single small process, and echoed the text `hello world`.

The process isn't running anymore. You can confirm that by running the command `docker ps`. You just ran an interactive process. Once the process completed, it stopped running. This might seem a little strange at first. Remember, containers are more like supercharged processes than like virtual machines.

Let's do something a little more sophisticated. Type in the following command:

  docker run -it ubuntu bash

This tells Docker to load the `ubuntu` image and run the `bash` command. Additionally, Docker was told to setup a virtual terminal connection to the container (-it). You should see the Docker client download the Ubuntu Linux image and launch the container. It may take a minute the first time you run this command.

Now that you are in the container terminal, look around a little bit. Type in `ls /` to view the root directory. Containers have their own filesystem that overlays the filesystem on the host. Exit out of the container terminal by typing `exit`.

Notice that the container you just launched is now stopped (`docker ps -a`). This was an interactive container just like the first container you created. Try to run the container again, type:

  docker run -it ubuntu bash

Did you notice how much faster the container launched this time? That's because Docker is pretty smart about caching the different build layers of the container. It knew how to build the container this time because it cached all the layers from the previous container. Exit out of the container again.

Next, let's launch a container that runs in the background named `web1`. Type in the command:

  docker run -d -P --name web1 nginx

This will download and create a container running the popular `nginx` webserver. You didn't specify a tag for the `nginx` image, so Docker defaults to using the `latest` tag. Note, the `latest` tag doesn't mean that Docker is necessarily using the latest image. It's just a default label and it can be applied to any image regardless of when the image was created.

When you create a container, Docker assigns it a long ID. It's not very easy to remember long ID strings, so using the `--name` parameter to assign a memorable name to containers is helpful. You should see this container running on the system. Check the Docker process list to confirm:

  docker ps

Look at the ports in the output that have been assigned to the web1 container.  You should see a a port mapping that looks similar to this: `0.0.0.0:32768->80/tcp`.  The nginx container image exposes port 80 in its dockerfile.  When you launched the container using the `-P` flag, Docker assigned a random port number (32768), and mapped it to the exposed port 80 on the container. Usually we want more control over the ports that a Docker container is exposing. We can use the `-p` (lowercase p) flag to map a network port inside the container to a port on the host system. Remember, Docker containers usually have their own network stack so the container networking environment is separate from the host.

Now, you should be able to retrieve the nginx test page using `curl` substituting <PORT_NUMBER> with the random port mapped to the container by Docker:

  curl localhost:<PORT_NUMBER>

You should see the html of the nginx test page displayed (`Welcome to nginx!`). Go ahead and stop this container (`docker stop <container ID>`) before proceeding.

=== Create a web page

Create a sub-directory in the ubuntu user's home directory called `docker`. Create another sub-directory within the `docker` directory called `html`. Create a small text file called `index.html` inside the `html` directory with the following content:

    <html>
    <body>
      <h1>Dynacorp Industries Website</h1>
    </body>
    </html>

The directory structure and location of the `index.html` file should look something like this:

====
&#x2523;docker +
&#x2503;&#160;&#160;&#x2517; html +
&#x2503;&#160;&#160;&#160;&#160;&#x2517; index.html +
====

=== The Dockerfile

A Dockerfile is a handy way to encapsulate all the configuration commands required to build a single container. The remaining part of your project this week is to build a simple nginx webserver container using a Dockerfile. Create the `Dockerfile` in the `docker` directory. Here are the configuration requirements for the Docker image:

  * The new image must be based off the `nginx` image.
  * Label the image with some metadata specifying your name and e-mail address like "Sarah Student <sarah@ilovedocker.com>".
  * The image should expose port 80.
  * Copy the files from the `html` directory you created earlier in the assignment to the /usr/share/nginx/html directory in the container.

Create a new Docker image called `dynacorpweb` with a tag of `1.0` using the Dockerfile. 

=== The Container

Now that you have a Docker image you can launch a container using that image. Launch a new container with the following configuration settings:

  * The name of the container should be `dynacorpweb1`.
  * The container should run in a detached (daemon) mode.
  * The container should map port 80 within the container to port 80 on the host server.
  * The container should have an environment variable mapping the key `DYNAWEB_DB` to the value `dynadb`.

Once the container is running you should be able to see the basic web page you added to the Docker image by using the curl command.

  curl localhost

=== Docker Compose file

Typically in a production environment we don't launch individual Docker containers manually. We use Docker Compose or a container orchestration platform to run containers (which we will talk about soon). Docker Compose uses a special YAML file to describe the runtime configuration settings for one or more containers. You can use the `docker-compose` command to create all of the container services defined in the configuration file:

    docker-compose up -d

Create a basic Docker compose file called `docker-compose.yaml` to launch the `dynacorpweb1` container. You can find documentation for Docker Compose at the following website:

    https://docs.docker.com/compose/


=== Ninja Rockstar task (optional)

It's common to store Docker images in a repository after the images are built, and this allows multiple systems and teams to share commonly used images across the enterprise. AWS provides a Docker repository service called the Elastic Container Registry (ECR). Create a CloudFormation template to build a new repository in ECR called `dynacorpweb`. Launch the stack and push the Docker image you created earlier into this Docker repository.

=== Show me your work

Please show me your Docker compose file code.

=== Terminate AWS resources

Remember to terminate all the resources created in this project.
